#!/usr/bin/env bash
set -Eeuo pipefail
# shellcheck source=../lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

require_ubuntu
arch=$(architecture)
home=$(target_home)
group=$(id -gn "$TARGET_USER")

install_bat() {
  local prefix="/opt/bat/$BAT_VERSION"
  should_install "$prefix/bin/bat" || return 0

  local tmp archive target binary
  tmp=$(make_temp_dir)
  archive="$tmp/bat.tar.gz"
  case "$arch" in
    x86_64) target=x86_64-unknown-linux-gnu ;;
    aarch64) target=aarch64-unknown-linux-gnu ;;
  esac

  github_download_asset sharkdp/bat "v$BAT_VERSION" \
    "^bat-v${BAT_VERSION}-${target}\\.tar\\.gz$" "$archive"
  tar -xzf "$archive" -C "$tmp"
  binary=$(find "$tmp" -type f -name bat -perm -u+x | head -n 1)
  [[ -n "$binary" ]] || die 'bat binary was not found after extraction'

  as_root rm -rf "$prefix"
  as_root mkdir -p "$prefix/bin"
  as_root install -m 0755 "$binary" "$prefix/bin/bat"
  rm -rf "$tmp"
}

install_eza() {
  local prefix="/opt/eza/$EZA_VERSION"
  should_install "$prefix/bin/eza" || return 0

  local tmp archive target binary
  tmp=$(make_temp_dir)
  archive="$tmp/eza.tar.gz"
  case "$arch" in
    x86_64) target=x86_64-unknown-linux-gnu ;;
    aarch64) target=aarch64-unknown-linux-gnu ;;
  esac

  github_download_asset eza-community/eza "v$EZA_VERSION" \
    "^eza_${target}\\.tar\\.gz$" "$archive"
  tar -xzf "$archive" -C "$tmp"
  binary=$(find "$tmp" -type f -name eza -perm -u+x | head -n 1)
  [[ -n "$binary" ]] || die 'eza binary was not found after extraction'

  as_root rm -rf "$prefix"
  as_root mkdir -p "$prefix/bin"
  as_root install -m 0755 "$binary" "$prefix/bin/eza"
  rm -rf "$tmp"
}

log "Installing bat $BAT_VERSION"
install_bat
link_system_binary "/opt/bat/$BAT_VERSION/bin/bat" bat

log "Installing eza $EZA_VERSION"
install_eza
link_system_binary "/opt/eza/$EZA_VERSION/bin/eza" eza

log 'Writing bat user configuration'
as_root install -o "$TARGET_USER" -g "$group" -d "$home/.config/bat"
bat_config=$(mktemp)
cat > "$bat_config" <<'EOF_BAT'
# Generated by ubuntu-dev-deploy.
--style=numbers,changes,header
--paging=auto
--tabs=4
EOF_BAT
as_root install -o "$TARGET_USER" -g "$group" -m 0644 "$bat_config" "$home/.config/bat/config"
rm -f "$bat_config"

log 'bat and eza installed and configured'
