#!/usr/bin/env bash
set -Eeuo pipefail
# shellcheck source=../lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

require_ubuntu
arch=$(architecture)
home=$(target_home)
group=$(id -gn "$TARGET_USER")
prefix="/opt/ccache/$CCACHE_VERSION"

if should_install "$prefix/bin/ccache"; then
  log "Installing ccache $CCACHE_VERSION"
  tmp=$(make_temp_dir)
  archive="$tmp/ccache.tar.xz"
  github_download_asset ccache/ccache "v$CCACHE_VERSION" \
    "^ccache-${CCACHE_VERSION}-linux-${arch}-glibc\\.tar\\.xz$" "$archive"
  mkdir -p "$tmp/extracted"
  tar -xJf "$archive" -C "$tmp/extracted"
  binary=$(find "$tmp/extracted" -type f -name ccache -perm -u+x | head -n 1)
  [[ -n "$binary" ]] || die 'ccache binary was not found after extraction'
  as_root rm -rf "$prefix"
  as_root mkdir -p "$prefix/bin"
  as_root install -m 0755 "$binary" "$prefix/bin/ccache"
  rm -rf "$tmp"
else
  log "ccache $CCACHE_VERSION is already installed"
fi

link_system_binary "$prefix/bin/ccache" ccache

log 'Writing ccache user configuration'
as_root install -o "$TARGET_USER" -g "$group" -d \
  "$home/.config/ccache" "$home/.cache/ccache"
ccache_config=$(mktemp)
cat > "$ccache_config" <<EOF_CCACHE
# Generated by ubuntu-dev-deploy.
cache_dir = $home/.cache/ccache
max_size = 20G
compression = true
compression_level = 6
compiler_check = content
EOF_CCACHE
as_root install -o "$TARGET_USER" -g "$group" -m 0644 \
  "$ccache_config" "$home/.config/ccache/ccache.conf"
rm -f "$ccache_config"

run_as_target env \
  HOME="$home" \
  CCACHE_CONFIGPATH="$home/.config/ccache/ccache.conf" \
  /usr/local/bin/ccache --zero-stats >/dev/null

log 'ccache installed and configured for CMake compiler launchers'
