#!/usr/bin/env bash
set -Eeuo pipefail
# shellcheck source=../lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

require_ubuntu
home=$(target_home)

log 'Writing system-wide environment defaults'
as_root tee /etc/profile.d/90-dev-tools.sh >/dev/null <<EOF_PROFILE
# Generated by ubuntu-dev-deploy.
export LANG=en_US.UTF-8
export LANGUAGE=en_US:en
export LC_ALL=en_US.UTF-8
export COLORTERM="\${COLORTERM:-truecolor}"
export CLICOLOR=1
export PATH="/usr/local/bin:\$HOME/.local/bin:\$HOME/.cargo/bin:\$PATH"
export MANPATH="/opt/tmux/$TMUX_VERSION/share/man:/opt/git/$GIT_VERSION/share/man:/opt/cmake/$CMAKE_VERSION/share/man:\${MANPATH:-}"
export EDITOR=nvim
export VISUAL=nvim
export UV_CACHE_DIR="\$HOME/.cache/uv"
export UV_TOOL_DIR="\$HOME/.local/share/uv/tools"
export UV_TOOL_BIN_DIR="\$HOME/.local/bin"
export RUFF_CACHE_DIR="\$HOME/.cache/ruff"
export PRE_COMMIT_HOME="\$HOME/.cache/pre-commit"
export CCACHE_CONFIGPATH="\$HOME/.config/ccache/ccache.conf"
export CMAKE_C_COMPILER_LAUNCHER=ccache
export CMAKE_CXX_COMPILER_LAUNCHER=ccache
export CMAKE_CUDA_COMPILER_LAUNCHER=ccache
EOF_PROFILE
as_root chmod 0644 /etc/profile.d/90-dev-tools.sh

COMMON_BLOCK='export LANG=en_US.UTF-8
export LANGUAGE=en_US:en
export LC_ALL=en_US.UTF-8
export COLORTERM="${COLORTERM:-truecolor}"
export CLICOLOR=1
export PATH="/usr/local/bin:$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
export EDITOR=nvim
export VISUAL=nvim
export UV_CACHE_DIR="$HOME/.cache/uv"
export UV_TOOL_DIR="$HOME/.local/share/uv/tools"
export UV_TOOL_BIN_DIR="$HOME/.local/bin"
export RUFF_CACHE_DIR="$HOME/.cache/ruff"
export PRE_COMMIT_HOME="$HOME/.cache/pre-commit"
export CCACHE_CONFIGPATH="$HOME/.config/ccache/ccache.conf"
export CMAKE_C_COMPILER_LAUNCHER=ccache
export CMAKE_CXX_COMPILER_LAUNCHER=ccache
export CMAKE_CUDA_COMPILER_LAUNCHER=ccache

[ -s "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"'

ZSH_BLOCK=$(cat <<EOF_ZSH
$COMMON_BLOCK

if [ -f /opt/fzf/$FZF_VERSION/shell/completion.zsh ]; then
  source /opt/fzf/$FZF_VERSION/shell/completion.zsh
  source /opt/fzf/$FZF_VERSION/shell/key-bindings.zsh
fi

[ -f "\$HOME/.local/share/dev-deploy/completions/uv.zsh" ] && source "\$HOME/.local/share/dev-deploy/completions/uv.zsh"
[ -f "\$HOME/.local/share/dev-deploy/completions/ruff.zsh" ] && source "\$HOME/.local/share/dev-deploy/completions/ruff.zsh"

alias ll='eza -lah --group-directories-first --git'
alias la='eza -a --group-directories-first'
alias l='eza -lah --group-directories-first'
alias tree='eza --tree --group-directories-first'

function yy() {
  local tmp cwd
  tmp="\$(mktemp -t yazi-cwd.XXXXXX)"
  yazi "\$@" --cwd-file="\$tmp"
  cwd="\$(cat -- "\$tmp")"
  [ -n "\$cwd" ] && [ "\$cwd" != "\$PWD" ] && builtin cd -- "\$cwd"
  rm -f -- "\$tmp"
}
EOF_ZSH
)
append_user_managed_block "$home/.zshrc" environment "$ZSH_BLOCK"

BASH_BLOCK=$(cat <<EOF_BASH
$COMMON_BLOCK

if [ -f /opt/fzf/$FZF_VERSION/shell/completion.bash ]; then
  source /opt/fzf/$FZF_VERSION/shell/completion.bash
  source /opt/fzf/$FZF_VERSION/shell/key-bindings.bash
fi

[ -f "\$HOME/.local/share/dev-deploy/completions/uv.bash" ] && source "\$HOME/.local/share/dev-deploy/completions/uv.bash"
[ -f "\$HOME/.local/share/dev-deploy/completions/ruff.bash" ] && source "\$HOME/.local/share/dev-deploy/completions/ruff.bash"

alias ll='eza -lah --group-directories-first --git'
alias la='eza -a --group-directories-first'
alias l='eza -lah --group-directories-first'
alias tree='eza --tree --group-directories-first'

yy() {
  local tmp cwd
  tmp="\$(mktemp -t yazi-cwd.XXXXXX)"
  yazi "\$@" --cwd-file="\$tmp"
  cwd="\$(cat -- "\$tmp")"
  [ -n "\$cwd" ] && [ "\$cwd" != "\$PWD" ] && builtin cd -- "\$cwd"
  rm -f -- "\$tmp"
}
EOF_BASH
)
append_user_managed_block "$home/.bashrc" environment "$BASH_BLOCK"

log 'Environment files updated for new Bash and Zsh sessions'
